### ISSUE TITLE
Pypi version missing the tribe-admin.py file

### ISSUE THREAD

**Issue by onlyphantom** [DistrictDataLabs/tribe#11]
If a user is to install through pypi (`pip install tribe`), the version that is installed does not include the `tribe-admin.py` file. 

As a result, following the instructions for pip install on the `README` would lead to the following:
`python: can't open file 'tribe-admin.py': [Errno 2] No such file or directory`

Should we update the README in the meantime to reflect that, and advise users to git clone instead while a fix is being submitted?

**Comment by bbengfort** [comment]
Hi @onlyphantom thanks for using Tribe! This project is getting a bit long in the tooth and is desperately in need of an update, both for new versions of Python networkx and for Python 3. I occasionally use this tool to extract a graph out of my email, but not really enough to convince me to do the rewrite. If you'd like to make updates to the library though, I'm happy to review them and contribute where I can!
