### ISSUE TITLE
No indication of status when processing

### ISSUE THREAD

**Issue by edglazer** [DistrictDataLabs/tribe#3]
Hi!
I'm very interested in this project. I have a significant mbox (~9GB, with 114957 emails according to the `count` command line modifier) and have been running the extract command for several hours on a modern, speedy cpu with no indication of status. Is there a way to see what's happened? Progress indicator?

Thanks!

**Comment by bbengfort** [comment]
@edglazer that's great to hear that you're using this tool! A progress indicator is a great idea, I can certainly put one in. 

How are you using the tool; did you clone the project from source or did you pip install it?

**Comment by bbengfort** [comment]
Well, here is my initial test using pyprind: 

![screenshot 2016-06-22 18 21 14](https://cloud.githubusercontent.com/assets/745966/16285783/373ec936-38a6-11e6-9a6c-62459369cda0.png)

As you can see, it takes half as much time just to get a count of the number of emails in a 5.7 GiB as it does to extract and analyze them (and increasing the total processing time by a significant amount).

I think it would be best to just add an elapsed time counter along with the total number of emails that have been processed so far. Hopefully that's ok.

**Comment by bbengfort** [comment]
And here is my custom version:

![screenshot 2016-06-22 19 12 13](https://cloud.githubusercontent.com/assets/745966/16286956/ca8e01b4-38ad-11e6-8eb5-ced8025c32c2.png)


The new issue is that time doesn't start elapsing for quite some time as the internal Python mbox reader loads up.

**Comment by bbengfort** [comment]
@edglazer ok, I've added a release with some progress information. If you're using pip, then simply:

    pip install -U tribe 

Make sure that tribe-admin.py --version is 1.2 -- otherwise do a pull for the latest in the repository! 

Good luck!

**Comment by edglazer** [comment]
Whoah! That was crazy fast! I ducked away for a couple days and you totally took this on! I did install via pip, so I'll try out your methods! Thanks so much for this cool set of tools!
