### ISSUE TITLE
Graph extraction appears to freeze or stop after parsing

### ISSUE THREAD

**Issue by edglazer** [DistrictDataLabs/tribe#4]
Hi again!
The updated tribe library and tools with progress are great! Tried updating via pip which worked great. Running the tribe-admin.py extraction updated me for 7 minutes 45 seconds, and parsed 114658 emails, but now is frozen. Is there a way to see errors, what's going on?

**Comment by bbengfort** [comment]
If that is the same number as when you run count, then what it is doing is attempting to write the graph out to disk. For this, it's simply using networkx, and not my code. On my 5GB email MBox it does take a minute or two to write out the graph, which is decently large. If it's been running for more than a minute or two, I'm not sure what's going on - especially if that errors, it should let you know. 

Could you open up a monitor and see how much memory it's using? Maybe the graph is so big that it's taking all of your memory and causing swap files to be written, which would be CRAZY slow.

**Comment by edglazer** [comment]
Its been going for about 5 hours, 99% CPU, and the OSX activity monitor shows 474 MB real memory used by python. I believe the email count is off by about 300.

**Comment by edglazer** [comment]
Incidentally, I have 32GB Ram on my system (though I don't actually know how much of that python can use?). But if you think the problem lies with networkX, maybe we can close this issue? Is there a way to determine that?

**Comment by bbengfort** [comment]
Well, in that case - it's certainly not it! 

If you look at the code, the `extract_graph` function does most of the work here on [extract.py L106](https://github.com/DistrictDataLabs/tribe/blob/master/tribe/extract.py#L106). The progress indicator that I put in will say 100%  on [L141](https://github.com/DistrictDataLabs/tribe/blob/master/tribe/extract.py#L141) -- after that, the MBox reading is over, and everything heads to NetworkX.

- Step 1 is Graph Creation: [L143](https://github.com/DistrictDataLabs/tribe/blob/develop/tribe/extract.py#L143)
- Step 2 is Graph Writing: [tribe-admin.py L89](https://github.com/DistrictDataLabs/tribe/blob/master/tribe-admin.py#L89)

Perhaps you could sprinkle in some print statements to see how far you're getting and what operation it's actually working through when it gets stuck? Just make sure to checkout the develop branch! 

After that, I'd want to use line_profile and or memory_profile to get a good look at what's happening on the internals. Have you used those tools before?

**Comment by edglazer** [comment]
I have now! Sure looks like the culprit might be networkX after all. Here's the line_profiler report:

Total time: 1401.2 s
File: tribe/extract.py
Function: extract_graph at line 105
<code><pre>
 Line #       Hits         Time  Per Hit   % Time  Line Contents
==============================================================
   105                                               @profile
   106                                               def extract_graph(self):
   107                                                   """
   108                                                   Extracts a Graph where the nodes are EmailAddress
   109                                                   """
   110
   111         1            3      3.0      0.0          def relationships(email):
   112                                                       """
   113                                                       Inner function that constructs email relationships
   114                                                       """
   115                                                       people = [email.sender,]
   116                                                       people.extend(email.recipients)
   117                                                       people.extend(email.copied)
   118
   119                                                       people = filter(lambda p: p is not None, people)            # Filter out any None addresses
   120                                                       people = set(addr.email for addr in people if addr.email)   # Obtain only unique people
   121                                                       people = sorted(people)                                     # Sort lexicographically for combinations
   122
   123                                                       for combo in combinations(people, 2):
   124                                                           yield combo
   125
   126
   127                                                   # Keep track of all the email to email links
   128         1           18     18.0      0.0          links = FreqDist()
   129
   130                                                   # Iterate over all the extracted emails
   131                                                   # Catch exceptions, if any, and move forward
   132                                                   # NOTE: This will allow the progress bar to work
   133                                                   # NOTE: This will build the graph data structure in memory
   134    114956   1159836727  10089.4     82.8          for email in self.extract():
   135    114955       136897      1.2      0.0              try:
   136   4870025      7657826      1.6      0.5                  for combo in relationships(email):
   137   4755070      7686760      1.6      0.5                      links[combo] += 1
   138                                                       except Exception as e:
   139                                                           self.errors[e] += 1
   140                                                           continue
   141
   142                                                   # Construct the networkx graph and add edges
   143         1           66     66.0      0.0          G = nx.Graph(name="Email Network", mbox=self.path, extracted=strfnow())
   144      4173        67408     16.2      0.0          for link in links.keys():
   145      4173    225812988  54112.9     16.1              G.add_edge(*link, weight=links.freq(link))
   146
   147                                                   # Return the generated graph
   148                                                   return G
</pre></code>

**Comment by bbengfort** [comment]
So you quit running after 1401 seconds, and it was still doing add edge? 

I have a couple of thoughts:

1. I can add a progress bar around the for link in link.keys() so you'll at least know that it's moving 
2. Maybe the links.freq() computation is too strenuous? Can you change that line of code to:

    ```python
    G.add_edge(*link, weight=links[link])
    ``` 

    This will give you a count of messages between that link rather than computing the frequency. 

3. We could detect if Graph Tool is installed (a C++ graph library with Python wrapper) and use it instead of NetworkX, this might cause a speedup.

**Comment by edglazer** [comment]
Yeah, sorry about the shortness of the run. I only ran it fairly briefly (on this occasion) because I was really interested to see what the profiler output would be. I had previously run tribe-admin extract overnight on one machine, and for about 7 hours on another, though unfortunately without the profiler.

Am I interpreting correctly, that it seems to complete the extraction (the "tribe piece"), and thus is getting bogged down somehow in the networkX graph construction?

I'm currently letting it run with memory_profiler to see what that shows. After letting that go for a 30-60 minute stretch, I'll try:
1. Changing the links.freq() code as suggested and let it run for a while (with profiler).
2. Changing the code back and letting it run for a longer sustained period (also with profiler).
3. Install Graph Tool (which I had found during my initial troubleshooting) and see how easy it would be to use that...?

Thanks again for your work on this. I wonder if something in my mac setup is the culprit?

**Comment by edglazer** [comment]
Tried modifying extract.py with the suggested code:
`G.add_edge(*link, weight=links[link])`

That worked, completing the parsing of 114855 emails in 18 minutes, 25 seconds.
Pertinent profiling info here (not sure why the code appears to be the same, even though I made the suggested change?):
```
   143         1           66     66.0      0.0          G = nx.Graph(name="Email Network", mbox=self.path, extracted=strfnow())
   144      4173        67408     16.2      0.0          for link in links.keys():
   145      4173    225812988  54112.9     16.1              G.add_edge(*link, weight=links.freq(link))
```
I also tried restoring the original code and running it for a longer go. I didn't clock it, but probably 60-90 minutes or longer. Here is pertinent output from the profiler:
```
143         1           58     58.0      0.0          G = nx.Graph(name="Email Network", mbox=self.path, extracted=strfnow())
144     90728       281650      3.1      0.0          for link in links.keys():
145     90728   4521475670  49835.5     80.5              G.add_edge(*link, weight=links.freq(link))
```

Also just discovered your dev blog by accident, in looking at what would be involved in running graph tool instead of networkX. Finally, I'm wondering if the 90728 cycles through the G.add_edge statement in the unmodified code suggest it just hadn't gotten through all the messages yet? Sorry to be such a pain!

**Comment by bbengfort** [comment]
Yep, you're right that the process has already run through all your emails, it is just not doing a very good job of adding all the edges to the graph. However, based on your profiling information I think I have an idea for a solution. Give me a few minutes to try to sort it out.

**Comment by bbengfort** [comment]
@edglazer ok I just did some work that will minimize the number of cycles required for G.add_edge; I wish I had added a progress bar there too, but let's see if it's faster. Upgrade your version of tribe:

```
$ pip install -U tribe 
$ python tribe-admin.py --version 
```

You should be at Version 1.3. Let me know if you gained any performance benefits (and if it finishes). I also added some more weights to the edges, so it's faster AND a better graph. 

For me, I gained an entire minute:

Before:

![timing pre hotfix](https://cloud.githubusercontent.com/assets/745966/16629176/d1a6c348-4382-11e6-9185-09afcfaddf92.png)

After:

![timing post hotfix](https://cloud.githubusercontent.com/assets/745966/16629182/d6d3b740-4382-11e6-97b4-e9d05a02d6c0.png)

**Comment by edglazer** [comment]
Forgot to report back after the long weekend, apologies! it did complete its run, taking over a day. Could be something funky about my particular mbox? In either case, it does work just fine.

**Comment by bbengfort** [comment]
Crazy! An entire day! Well, hopefully you have an awesome graph to show for it - any visualizations yet?
